[package]
name = "mobius"
version = "0.1.0"
authors = ["Nick Platt <platt.nicholas@gmail.com>"]
edition = "2018"

[dependencies]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

