[package]
name = "mobius"
version = "0.1.0"
authors = ["Nick Platt <platt.nicholas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.7.2"
crossbeam-channel = "0.3.8"
rayon = "1.1.0"
